session_name: hexapod
windows:
  - window_name: sitl and gazebo
    layout: tiled
    shell_command_before:
      - killall gzserver
      - killall gzclient
      - cd /home/user/projects/hexapod/
    panes:
      - shell_command: # pane no. 1
          - source env.sh
          - gazebo --verbose hexapod.sdf
      


