session_name: quadruped
windows:
  - window_name: sitl and gazebo
    layout: tiled
    shell_command_before:
      - killall gzserver
      - killall gzclient
      - cd /home/user/projects/hexapod/
    panes:
      - shell_command: # pane no. 1
          - source env.sh
          - gazebo --verbose quadruped.world
      - shell_command:
          - cd hexapod_bringup
          - ./bin/ardurover -S --model gazebo-rover \
            --speedup 1 \
            --defaults /home/user/projects/hexapod/hexapod_bringup/params/quadruped.parm \
            -I1
      - shell_command:
          - sleep 3
          - mavproxy.py --master tcp:127.0.0.1:5760 --out=udp:127.0.0.1:14550
      


